package cricketanalyser;

public enum SortField {
    AVERAGE, MAX6SAND4S, STRIKE_RATE, TOTALSIXANDFOR, AVERAGEWITHSTRKIERATE, EconomyRate, TOTAL4W5W, BESTSTRIKE, BESTAVERAGE, MAXIMUMWICKETWITHAVERAGE, RUNS
}
